spring.datasource.url=jdbc:mysql://localhost:3306/ghostnet?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=LEMdisco10999!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
spring.application.name=ghostnet
